# Generated by Django 5.1.2 on 2024-11-07 13:55

from django.db import migrations

def migrate_author_to_contributors(apps, schema_editor):
    Blog = apps.get_model('blog', 'Blog')
    for blog in Blog.objects.all():
        if blog.author:
            blog.contributors.add(
                blog.author, through_defaults={'contribution': 'Auteur principal'})


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_author_blogcontributor_blog_contributors_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_author_to_contributors)
    ]
